[2024-07-19T18:13:19.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T18:13:19.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-19T18:13:05.641856+00:00 [queued]>
[2024-07-19T18:13:19.951+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-19T18:13:05.641856+00:00 [queued]>
[2024-07-19T18:13:19.958+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T18:13:20.051+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_ledger_account_s> on 2024-07-19 18:13:05.641856+00:00
[2024-07-19T18:13:20.103+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_ledger_account_s', 'manual__2024-07-19T18:13:05.641856+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpuksxqpnb']
[2024-07-19T18:13:20.103+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3824) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T18:13:20.132+0000] {standard_task_runner.py:64} INFO - Started process 3844 to run task
[2024-07-19T18:13:20.130+0000] {standard_task_runner.py:91} INFO - Job 369: Subtask md_ledger_account_s
[2024-07-19T18:13:20.377+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_ledger_account_s manual__2024-07-19T18:13:05.641856+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T18:13:20.794+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_ledger_account_s' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:13:05.641856+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T18:13:05.641856+00:00'
[2024-07-19T18:13:20.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T18:13:20.915+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T18:13:21.174+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T18:13:21.191+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T18:13:21.276+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_ledger_account_s, run_id=manual__2024-07-19T18:13:05.641856+00:00, execution_date=20240719T181305, start_date=20240719T181319, end_date=20240719T181321
[2024-07-19T18:13:21.392+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T18:13:21.495+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T18:13:21.499+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
