[2024-07-19T18:07:12.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T18:07:12.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_posting_f manual__2024-07-19T18:06:55.309501+00:00 [queued]>
[2024-07-19T18:07:12.807+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_posting_f manual__2024-07-19T18:06:55.309501+00:00 [queued]>
[2024-07-19T18:07:12.809+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T18:07:12.874+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ft_posting_f> on 2024-07-19 18:06:55.309501+00:00
[2024-07-19T18:07:12.942+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3731) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T18:07:12.949+0000] {standard_task_runner.py:64} INFO - Started process 3740 to run task
[2024-07-19T18:07:12.949+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_posting_f', 'manual__2024-07-19T18:06:55.309501+00:00', '--job-id', '361', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpjs9jhhjn']
[2024-07-19T18:07:12.963+0000] {standard_task_runner.py:91} INFO - Job 361: Subtask ft_posting_f
[2024-07-19T18:07:13.168+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.ft_posting_f manual__2024-07-19T18:06:55.309501+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T18:07:14.365+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_posting_f' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:06:55.309501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T18:06:55.309501+00:00'
[2024-07-19T18:07:14.410+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T18:07:14.718+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T18:07:16.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T18:07:16.106+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "OPER_DATE" of relation "ft_posting_f" does not exist
LINE 1: INSERT INTO ds.ft_posting_f ("OPER_DATE", "CREDIT_ACCOUNT_RK...
                                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data.py", line 13, in insert_data
    df.to_sql(table_name, engine, schema="ds", if_exists="append", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "OPER_DATE" of relation "ft_posting_f" does not exist
LINE 1: INSERT INTO ds.ft_posting_f ("OPER_DATE", "CREDIT_ACCOUNT_RK...
                                     ^

[SQL: INSERT INTO ds.ft_posting_f ("OPER_DATE", "CREDIT_ACCOUNT_RK", "DEBET_ACCOUNT_RK", "CREDIT_AMOUNT", "DEBET_AMOUNT") VALUES (%(OPER_DATE)s, %(CREDIT_ACCOUNT_RK)s, %(DEBET_ACCOUNT_RK)s, %(CREDIT_AMOUNT)s, %(DEBET_AMOUNT)s)]
[parameters: ({'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 13630, 'DEBET_ACCOUNT_RK': 17436, 'CREDIT_AMOUNT': 94333.93, 'DEBET_AMOUNT': 18337.76}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 15698716, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 68294.14, 'DEBET_AMOUNT': 31542.06}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 12048338, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 2192.96, 'DEBET_AMOUNT': 98734.33}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 393808409, 'DEBET_ACCOUNT_RK': 17244, 'CREDIT_AMOUNT': 44179.86, 'DEBET_AMOUNT': 98544.65}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 409685020, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 18843.05, 'DEBET_AMOUNT': 889.74}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 10006159, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 82792.29, 'DEBET_AMOUNT': 15395.98}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 393808409, 'DEBET_ACCOUNT_RK': 17132, 'CREDIT_AMOUNT': 9587.62, 'DEBET_AMOUNT': 40751.1}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 23463, 'DEBET_ACCOUNT_RK': 13631, 'CREDIT_AMOUNT': 36873.02, 'DEBET_AMOUNT': 78441.61}  ... displaying 10 of 33892 total bound parameter sets ...  {'OPER_DATE': '31-01-2018', 'CREDIT_ACCOUNT_RK': 13630, 'DEBET_ACCOUNT_RK': 17627064, 'CREDIT_AMOUNT': 70839.11, 'DEBET_AMOUNT': 93751.76}, {'OPER_DATE': '31-01-2018', 'CREDIT_ACCOUNT_RK': 13630, 'DEBET_ACCOUNT_RK': 1648686, 'CREDIT_AMOUNT': 34785.31, 'DEBET_AMOUNT': 40997.1})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-07-19T18:07:16.155+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=insert_data, task_id=ft_posting_f, run_id=manual__2024-07-19T18:06:55.309501+00:00, execution_date=20240719T180655, start_date=20240719T180712, end_date=20240719T180716
[2024-07-19T18:07:16.194+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 361 for task ft_posting_f ((psycopg2.errors.UndefinedColumn) column "OPER_DATE" of relation "ft_posting_f" does not exist
LINE 1: INSERT INTO ds.ft_posting_f ("OPER_DATE", "CREDIT_ACCOUNT_RK...
                                     ^

[SQL: INSERT INTO ds.ft_posting_f ("OPER_DATE", "CREDIT_ACCOUNT_RK", "DEBET_ACCOUNT_RK", "CREDIT_AMOUNT", "DEBET_AMOUNT") VALUES (%(OPER_DATE)s, %(CREDIT_ACCOUNT_RK)s, %(DEBET_ACCOUNT_RK)s, %(CREDIT_AMOUNT)s, %(DEBET_AMOUNT)s)]
[parameters: ({'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 13630, 'DEBET_ACCOUNT_RK': 17436, 'CREDIT_AMOUNT': 94333.93, 'DEBET_AMOUNT': 18337.76}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 15698716, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 68294.14, 'DEBET_AMOUNT': 31542.06}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 12048338, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 2192.96, 'DEBET_AMOUNT': 98734.33}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 393808409, 'DEBET_ACCOUNT_RK': 17244, 'CREDIT_AMOUNT': 44179.86, 'DEBET_AMOUNT': 98544.65}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 409685020, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 18843.05, 'DEBET_AMOUNT': 889.74}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 10006159, 'DEBET_ACCOUNT_RK': 13630, 'CREDIT_AMOUNT': 82792.29, 'DEBET_AMOUNT': 15395.98}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 393808409, 'DEBET_ACCOUNT_RK': 17132, 'CREDIT_AMOUNT': 9587.62, 'DEBET_AMOUNT': 40751.1}, {'OPER_DATE': '09-01-2018', 'CREDIT_ACCOUNT_RK': 23463, 'DEBET_ACCOUNT_RK': 13631, 'CREDIT_AMOUNT': 36873.02, 'DEBET_AMOUNT': 78441.61}  ... displaying 10 of 33892 total bound parameter sets ...  {'OPER_DATE': '31-01-2018', 'CREDIT_ACCOUNT_RK': 13630, 'DEBET_ACCOUNT_RK': 17627064, 'CREDIT_AMOUNT': 70839.11, 'DEBET_AMOUNT': 93751.76}, {'OPER_DATE': '31-01-2018', 'CREDIT_ACCOUNT_RK': 13630, 'DEBET_ACCOUNT_RK': 1648686, 'CREDIT_AMOUNT': 34785.31, 'DEBET_AMOUNT': 40997.1})]
(Background on this error at: https://sqlalche.me/e/14/f405); 3740)
[2024-07-19T18:07:16.249+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T18:07:16.298+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T18:07:16.301+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
